# Site settings
title: Oman
client:
  name: Oman - Der Glanz des Sultanats
  link: "https://www.experienceoman.om"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Willkommen im Sultanat Oman – einem kulturreichen Land, das auf eine jahrtausendealte Geschichte zurückblickt. Erleben Sie die Kontraste zwischen dem tiefblauen Arabischen Meer und der größten Sandwüste der Welt, zwischen trockenen Flussläufen und saftig grünen Oasen.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/oman" # the subpath of your site, e.g. /blog/
img:     "/de/oman/_assets/img"
css:     "/de/oman/_assets/css"
js:      "/de/oman/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
